DROP SCHEMA IF EXISTS Movies;

CREATE SCHEMA Movies;
USE Movies;

CREATE TABLE Actors (
actor_id INT AUTO_INCREMENT PRIMARY KEY,
actor_name VARCHAR(50),
birthday DATE,
actor_image_directory VARCHAR(75)
);

CREATE TABLE Movies (
movie_id INT AUTO_INCREMENT PRIMARY KEY,
movie_name VARCHAR(100),
movie_release_date DATE,
movie_director VARCHAR(50),
movie_description VARCHAR(300),
movie_image_directory VARCHAR(100)
);

CREATE TABLE Quotes (
quote_id INT AUTO_INCREMENT PRIMARY KEY,
quote_line VARCHAR (200),
actor_id INT, 
FOREIGN KEY (actor_id) REFERENCES Actors(actor_id),
movie_id INT,
FOREIGN KEY (movie_id) REFERENCES Movies(movie_id),
quote_url VARCHAR(500)
);

CREATE TABLE Hints (
hint_id INt AUTO_INCREMENT PRIMARY KEY,
actor_id INT,
FOREIGN KEY (actor_id) REFERENCES Actors(actor_id),
hint VARCHAR(250)
);

CREATE TABLE ActorMovies (
actor_id INT NOT NULL,
movie_id INT NOT NULL,
primary key (actor_id, movie_id),
FOREIGN KEY (actor_id) REFERENCES Actors(actor_id),
FOREIGN KEY (movie_id) REFERENCES Movies(movie_id)
);

INSERT INTO Actors (actor_name, birthday, actor_image_directory) VALUES
('Samuel L. Jackson', '1948-12-21', 'SamJackson'),
('Anya Taylor-Joy', '1996-04-16', 'AnyaTaylorJoy'),
('Andrew Garfield', '1983-08-20', 'AndrewGarfield'),
('Robert Redford', '1936-08-18', 'RobertRedford'),
('Jennifer Lawrence', '1990-08-15', 'JenniferLawrence'),
('Elizabeth Olsen', '1989-02-16', 'ElizabethOlsen'),
('Tom Hanks', '1956-07-09', 'TomHanks'),
('Zendaya Coleman', '1996-09-01', 'Zendaya'),
('Hunter Schafer', '1998-12-31', 'HunterSchafer'),
('Margaret Qualley', '1994-10-23', 'MargaretQualley'),
('Florence Pugh', '1996-01-03', 'FlorencePugh'),
('Meryl Streep', '1949-06-22', 'MerylStreep'),
('Marlon Brando', '1924-04-03', 'MarlonBrando'),
('Judy Garland', '1922-06-10', 'JudyGarland'),
('Tom Cruise', '1962-07-03', 'TomCruise'),
('Elle Fanning', '1998-04-09', 'ElleFanning');

INSERT INTO Movies (movie_name, movie_release_date, movie_director, movie_description, movie_image_directory) VALUES
('Pulp Fiction', '1994-10-14', 'Quentin Tarantino', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'PulpFiction'),
('The Long Kiss Goodnight', '1996-10-07', 'Renny Harlin', 'Government agents come after an amnesiac woman, who gradually remembers her past.', 'TheLongKissGoodnight'),
('Unbreakable', '2000-11-22', 'M. Night Shyamalan', 'A man learns something extraordinary about himself after a devastating accident.', 'Unbreakable'),
('Coach Carter', '2005-01-14', 'Thomas Carter', 'Controversy surrounds high school basketball coach Ken Carter after he benches his entire team for breaking their academic contract with him.', 'CoachCarter'),
('A Time To Kill', '1996-07-24', 'Joel Schumacher', 'A young Mississippi lawyer defends a black man who killed the two white men that assaulted his preteen daughter.', 'ATimeToKill'),
('The Menu', '2022-11-18', 'Mark Mylod', 'A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.', 'TheMenu'),
('The Witch', '2016-02-19', 'Robert Eggers', 'In 1630, a farmer relocates his family to a remote plot of land on the edge of a forest where strange, unsettling things happen.', 'TheWitch'),
('Split', '2017-01-20', 'M. Night Shyamalan', 'A man with multiple personalities abducts three teenage girls, forcing them to adapt and survive as he reveals his hidden persona.', 'Split'),
('Glass', '2019-01-18', 'M. Night Shyamalan', 'Security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities.', 'Glass'),
('The Social Network', '2010-10-01', 'David Fincher','As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea and by the co-founder who was later squeezed out of the business.', 'TheSocialNetwork'),
('Tick Tick Boom', '2021-11-19', 'Lin-Manuel Miranda', 'On the brink of turning 30, a promising theater composer navigates love, friendship and the pressure to create something great before time runs out.', 'TickTickBoom'),
('The Amazing Spider-Man', '2012-07-03', 'Marc Webb', 'After being bitten by a genetically altered spider, Peter Parker gains incredible powers and becomes Spider-Man.', 'TheAmazingSpiderman'),
('The Amazing Spider-Man 2', '2014-05-02', 'Marc Webb', 'Spider-Man faces new challenges as he confronts Electro and Green Goblin while trying to protect Gwen Stacy.', 'TheAmazingSpiderman2'),
('Hacksaw Ridge', '2016-11-04', 'Mel Gibson', 'WWII American Army Medic Desmond T. Doss refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.', 'HacksawRidge'),
('Butch Cassidy and the Sundance Kid', '1969-09-24', 'George Roy Hill', 'In 1890s Wyoming, Butch Cassidy and The Sundance Kid lead a band of outlaws and flee a relentless posse after a train robbery goes wrong.', 'ButchCassidyAndTheSundanceKid'),
('The Sting', '1973-12-25', 'George Roy Hill', 'Two grifters team up to pull off the ultimate con against a mob boss.', 'TheSting'),
('All the President’s Men', '1976-04-09', 'Alan J. Pakula', 'The Washington Post reporters uncover the Watergate scandal that leads to the resignation of President Nixon.', 'AllThePresidentsMen'),
('The Natural', '1984-05-11', 'Barry Levinson', 'An unknown baseball player with a mysterious past comes to the big leagues and inspires his team to win.', 'TheNatural'),
('The Old Man & the Gun', '2018-09-28', 'David Lowery', 'Based on the true story of Forrest Tucker, who escaped from San Quentin and carried out an unprecedented string of heists.', 'TheOldManAndTheGun'),
('Don\'t Look Up', '2021-12-10', 'Adam McKay', 'Two low-level astronomers must go on a giant media tour to warn humankind of an approaching comet that will destroy planet Earth.', 'DontLookUp'),
('The Hunger Games', '2012-03-23', 'Gary Ross', 'Katniss Everdeen volunteers to take her sister\'s place in a televised fight to the death.', 'TheHungerGames'),
('Silver Linings Playbook', '2012-11-21', 'David O. Russell', 'After a stint in a mental institution, a former teacher meets a mysterious woman with her own problems.', 'SilverLiningsPlaybook'),
('American Hustle', '2013-12-13', 'David O. Russell', 'A con artist and his partner are forced to work for a wild FBI agent to catch corrupt politicians.', 'AmericanHustle'),
('Joy', '2015-12-25', 'David O. Russell', 'A woman rises to become founder of a powerful business dynasty.', 'Joy'),
('Wind River', '2017-08-04', 'Taylor Sheridan', 'An FBI agent teams with a veteran tracker to investigate a murder on a Native American reservation.', 'WindRiver'),
('Avengers: Age of Ultron', '2015-05-01', 'Joss Whedon', 'Earth\'s mightiest heroes must reunite to stop the villainous Ultron from enacting his plan of human extinction.', 'AvengersAgeOfUltron'),
('Doctor Strange in the Multiverse of Madness', '2022-05-06', 'Sam Raimi', 'Doctor Strange and Wanda Maximoff traverse alternate realities to face unimaginable consequences.', 'DoctorStrangeInTheMultiverseOfMadness'),
('Forrest Gump', '1994-07-06', 'Robert Zemeckis', 'A simple man with a low IQ recounts his extraordinary life and the events that shaped him.', 'ForrestGump'),
('Cast Away', '2000-12-22', 'Robert Zemeckis', 'After a plane crash, a FedEx employee struggles to survive alone on a deserted island.', 'CastAway'),
('Saving Private Ryan', '1998-07-24', 'Steven Spielberg', 'U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 'SavingPrivateRyan'),
('Big', '1988-06-03', 'Penny Marshall', 'A young boy makes a wish to be big and wakes up as an adult.', 'Big'),
('Catch Me If You Can', '2002-12-25', 'Steven Spielberg', 'The true story of Frank Abagnale Jr., who successfully conned millions of dollars before his 19th birthday.', 'CatchMeIfYouCan'),
('Dune', '2021-10-22', 'Denis Villeneuve', 'Paul Atreides arrives on Arrakis after his father accepts stewardship of the dangerous planet. Chaos ensues after betrayal as forces clash for control of spice.', 'Dune'),
('Spider-Man: Homecoming', '2017-07-07', 'Jon Watts', 'Peter Parker balances high school life with being Spider-Man under Tony Stark\'s mentorship.', 'SpidermanHomecoming'),
('The Greatest Showman', '2017-12-20', 'Michael Gracey ', 'The story of American showman P.T. Barnum, founder of the circus that became the famous traveling Ringling Bros. and Barnum & Bailey Circus.', 'TheGreatestShowman'),
('Challengers', '2024-04-26', 'Luca Guadagnino', 'A tennis coach faces off against her husband and ex-lover in a competitive tournament.', 'Challengers'),
('Cuckoo', '2024-08-29', 'Tilman Singer', 'A 17-year-old is forced to move with her family to a resort where things are not what they seem.', 'Cuckoo'),
('Belle', '2021-07-16', 'Mamoru Hosoda', 'A shy high school student becomes a world-famous singer in a massive virtual world.', 'Belle'),
('The Hunger Games: The Ballad of Songbirds and Snakes', '2023-11-17', 'Francis Lawrence', 'Coriolanus Snow mentors Lucy Gray Baird during the 10th Hunger Games.', 'TheHungerGamesTheBalladOfSongbirdsAndSnakes'),
('The Substance', '2024-09-20', 'Coralie Fargeat', 'Fading actress Elisabeth Sparkle becomes distressed when her chauvinistic boss fires her from her aerobics show. She soon injects herself with a mysterious serum that promises a younger, better version of herself, but things go horribly wrong.', 'TheSubstance'),
('Death Note', '2017-08-24', 'Adam Wingard', 'A young man finds a supernatural notebook and uses it to mete out death, attracting the attention of a detective, a demon and a girl in his class.', 'DeathNote'),
('Once Upon a Time in Hollywood', '2019-07-26', 'Quentin Tarantino', 'A struggling actor specializing in westerns, and a stuntman try to survive in a constantly changing movie industry.', 'OnceUponATimeInHollywood'),
('Honey, don\'t!', '2025-08-27', 'Ethan Coen', 'A small-town private investigator delves into a series of strange deaths tied to a mysterious church.', 'HoneyDont'),
('Drive-Away Dolls', '2024-02-22', 'Ethan Coen', 'In search of a fresh start, two best friends embark on an impromptu road trip to Tallahassee, but things quickly go awry when they cross paths with a group of inept criminals along the way.', 'DriveAwayDolls'),
('Midsommar', '2019-07-03', 'Ari Aster', 'A couple travels to Sweden for a rural festival, which becomes increasingly disturbing.', 'Midsommar'),
('Little Women', '2019-12-25', 'Greta Gerwig', 'The March sisters grow up during the Civil War, navigating love, loss, and independence.', 'LittleWomen'),
('Fighting with My Family', '2019-02-14', 'Stephen Merchant', 'A former wrestler and his family make a living performing at small venues around the country while his kids dream of joining World Wrestling Entertainment.', 'FightingWithMyFamily'),
('Black Widow', '2021-07-09', 'Cate Shortland', 'Natasha Romanoff confronts her dark past after the events of Avengers: Endgame.', 'BlackWidow'),
('We Live in Time', '2024-10-18', 'John Crowley', 'After an unusual encounter, a talented chef and a recently divorcée fall in love and build the home and family they\'ve always dreamed of, until a painful truth puts their love story to the test.', 'WeLiveInTime'),
('The Devil Wears Prada', '2006-06-30', 'David Frankel', 'An aspiring journalist starts working as an assistant to one of the city\'s biggest high fashion magazine editors', 'TheDevilWearsPrada'),
('Kramer vs. Kramer', '1979-12-19', 'Robert Benton', 'A just-divorced man must learn to care for his son on his own, and then must fight in court to keep custody of him.', 'KramerVsKramer'),
('Sophies Choice', '1982-12-08', 'Alan J. Pakula', 'A woman struggles with haunting memories from WWII.', 'SophiesChoice'),
('Mamma Mia!', '2008-07-18', 'Phyllida Lloyd', 'An independent hotelier is preparing for her daughter\'s wedding with the help of two old friends. Meanwhile Sophie, the spirited bride, has a plan.', 'MammaMia'),
('The Godfather', '1972-03-24', 'Francis Ford Coppola', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'TheGodfather'),
('A Streetcar Named Desire', '1951-09-18', 'Elia Kazan', 'Disturbed Blanche DuBois moves in with her sister in New Orleans and is tormented by her brutish brother-in-law while her reality crumbles around her.', 'AStreetcarNamedDesire'),
('On the Waterfront', '1954-07-28', 'Elia Kazan', 'A dockworker stands up to corruption.', 'OnTheWaterfront'),
('Apocalypse Now', '1979-08-15', 'Francis Ford Coppola', 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.', 'ApocalypseNow'),
('The Wild One', '1953-12-30', 'László Benedek', 'Two rival motorcycle gangs terrorize a small town after one of their leaders is thrown in jail.', 'TheWildOne'),
('Superman: The Movie', '1978-12-15', 'Richard Donner', 'An alien orphan is sent from his dying planet to Earth, where he grows up to become his adoptive home\'s first and greatest superhero.', 'Superman78'),
('The Wizard of Oz', '1939-08-25', 'Victor Fleming', 'A young girl is swept away by a tornado to a magical land', 'TheWizardOfOz'),
('A Star Is Born', '1954-09-29', 'George Cukor', 'A rising star falls in love with an actor past his prime and struggling with personal issues', 'AStarIsBorn'),
('Meet Me in St. Louis', '1944-11-28', 'Vincente Minnelli', 'Young love and childish fears highlight a year in the life of a turn-of-the-century family.', 'MeetMeInStLouis'),
('Easter Parade', '1948-06-30', 'Charles Walters', 'A dancer searches for a new partner.', 'EasterParade'),
('Judgment at Nuremberg', '1961-12-18', 'Stanley Kramer', 'Judges confront Nazi war crimes.', 'JudgementAtNuremberg'),
('Top Gun', '1986-05-16', 'Tony Scott', 'When hotshot fighter pilot is sent to a navy school, his reckless attitude and cocky demeanor put him at odds with the other pilots', 'TopGun'),
('Mission Impossible: Ghost Protocol', '2011-12-21', 'Brad Bird', 'A spy and his team must go rogue when they\'re framed for bombing the Kremlin', 'MissionImpossibleGhostProtocol'),
('Magnolia', '1999-12-10', 'Paul Thomas Anderson', 'An epic mosaic of interrelated characters in search of love, forgiveness and meaning in the San Fernando Valley', 'Magnolia'),
('Risky Business', '1983-08-05', 'Paul Brickman', 'A Chicago teenager is looking for fun at home while his parents are away, but the situation quickly gets out of hand.', 'RiskyBusiness'),
('Edge of Tomorrow', '2014-06-06', 'Doug Liman', 'A man fighting in a war against aliens must relive the same day every time he dies until he can find a way to stop their power source with the help of an elite soldier.', 'EdgeOfTomorrow'),
('Predator: Badlands', '2025-11-07', 'Dan Trachtenberg', 'Cast out from its clan, an alien hunter and an unlikely ally embark on a treacherous journey in search of the ultimate adversary.', 'PredatorBadlands'),
('Mary Shelley', '2018-07-06', 'Haifaa al-Mansour', 'The life of Mary Wollstonecraft Godwin, who at 16 met 21-year-old poet Percy Shelley, resulting in the writing of "Frankenstein".', 'MaryShelley'),
('All the Bright Places', '2020-02-28', 'Brett Haley', 'After meeting each other, two teenagers struggle with the emotional and physical scars of their pasts. They discover that even the smallest moments can mean something.', 'AllTheBrightPlaces'),
('Sentimental Value', '2025-11-14', 'Joachim Trier', 'An intimate exploration of family, memories, and the reconciliatory power of art.', 'SentimentalValue');

INSERT INTO Quotes (quote_line, actor_id, movie_id, quote_url) VALUES
('Mmm, This Is A Tasty Burger!', 1, 1, 'https://www.youtube.com/watch?v=JE8xhfx4u58'),
('I don\'t remember asking you a goddamn thing!', 1, 1, 'https://www.youtube.com/watch?v=JE8xhfx4u58'),
('Now that... is a cheeseburger.', 2, 6, 'https://www.youtube.com/watch?v=Pls7lt9Fz-E'),
('You better lawyer up, because I\'m not coming back for 30%, I\'m coming back for EVERYTHING.', 3, 10, 'https://www.youtube.com/watch?v=tjMGuJMIgwM'),
('You just keep thinking, Butch. That\'s what you\'re good at', 4, 15, NULL),
('I\'m not on a diet. I\'m just crying five times a day', 5, 20, NULL),
('You break the rules and become a hero. I do it and I become the enemy. That doesn\'t seem fair', 6, 27, 'https://www.youtube.com/watch?v=QbB_GLAUOTQ'),
('Stupid is as stupid does', 7, 28, 'https://www.youtube.com/watch?v=BRYqNfHcJsE'),
('My planet Arrakis is so beautiful when the sun is low. Rolling over the sands. You can see spice in the air', 8, 33, NULL),
('We\'ve gotten through worse than this. Snow lands on top', 9, 39, NULL),
('CONTROL YOURSELF!', 10, 40, NULL),
('I\'m making a mold of my foot for Laurie to remind him I have nice feet', 11, 46, NULL),
('By all means, move at a glacial pace', 12, 50, NULL),
('I\'m gonna make him an offer he can\'t refuse', 13, 54, 'https://www.youtube.com/watch?v=D6me2-OurCw'),
('I think we\'re not in Kansas, anymore', 14, 60, 'https://www.youtube.com/watch?v=1N77NaxlGlU'),
('I feel the need... the need for speed', 15, 65, NULL),
('But now, misery has come home, and men appear to me as monsters, thirsting for each other\'s blood. And I, a miserable spectacle of wrecked humanity, pitiable to others, and intolerable to myself.', 16, 71, NULL);

INSERT INTO Hints (actor_id, hint) VALUES
(1, 'This person was an usher at Martin Luther King\'s funeral'),
(1, 'This person is known to actively enjoy watching their own movies'),
(1, 'This person has a clause in their movie contracts that states they are required easy access to golf courses'),
(1, 'This actor/actress is known for their frequent use of the F bomb'),
(1, 'This actor/actress is close friends with Simon Pegg'),
(2, 'This actor/actress was discovered as a model whilst walking their dog'),
(2, 'This person is a fluent Spanish speaker who learned English by reading Harry Potter'),
(2, 'This actor/actress had their first lead role in a Robert Eggers film'),
(2, 'This person is an insomniac'),
(2, 'This person has recieved many accolades including a Golden Globe award in 2020'),
(3, 'This person is known for their chemistry and flirtations with someone who takes people on chicken shop dates'),
(3, 'This person played a superhero'),
(3, 'This person is close friends with Robert Pattinson and Matt Smith'),
(3, 'This actor/actress does not participate in social media'),
(3, 'This persons father is a swimmming coach'),
(4, 'This actor/actress passed away in 2025'),
(4, 'This person dislikes watching his own films'),
(4, 'This actor/actress was considered for a prominent role in the Godfather'),
(4, 'This persons daughter, Shauna, was in a relationship someone who was then murdered on August 1, 1983. The prime suspect has been on the run since 1986 over theft charges.'),
(4, 'This person was once voted the 30th greatest movie star of all time by Entertainment Weekly'),
(5, 'This person once dated an actor who played Lex Luthor'),
(5, 'This actor/actress auditioned for a prominent role in Twilight but lost'),
(5, 'This actor/actress was the second person to play a prominent Marvel character in live action'),
(5, 'This person once had to eat a raw fish for one of their movies'),
(5, 'This person is most well known for playing a character named K______'),
(6, 'This person has two famous sisters'),
(6, 'This actor/actresses favorite film growing up was Tremors'),
(6, 'This person auditioned for a prominent role in Michael Bay\'s TMNT movies, but lost out'),
(6, 'This actor/actress\' middle name is Chase because their parents want them to chase after their siblings'),
(6, 'This person was almost a lead in the new Star Wars trilogy but had scheduling conflicts'),
(7, 'This actor/actress attended Princess Diana\'s funeral'),
(7, 'This person is good friends with Bruce Springsteen'),
(7, 'This person stars in Caleb O\'Haras favorite movie of all time'),
(7, 'This person sold popcorn and peanuts as a teenager'),
(7, 'This person gained 55 pounds and then lost it for a role in a 2000 movie'),
(8, 'This actor/actress is close friends with Hunter Schafer'),
(8, 'This person was in a Kidz Bop music video'),
(8, 'This person was offered a prominent role in a Marvel movie but said no'),
(8, 'This actor/actress is a big fan of Law&Order SVU'),
(8, 'Both of this persons parents are teachers'),
(9, 'This persons first acting role was in a popular HBO television series'),
(9, 'This person studied art in University'),
(9, 'This actor/actress was in prominent headlines in 2016 for their activism'),
(9, 'This person was heavily fancast as a popular video game character, but lost the role to someone else'),
(9, 'This actor/actress was born in New Jersey'),
(10, 'This actor/actress has appeared in 3 films that have been nominated for best picture since 2019'),
(10, 'This person attended New York University for one semester'),
(10, 'This person has mentioned one of their big inspirations is a character from "Who framed Roger Rabbit?"'),
(10, 'This actor/actress is considered to be a nepo baby'),
(11, 'This actor/actress suffered from tracheomalacia as a child'),
(11, 'This person is known for playing a Marvel character who makes Mac n Cheese with hot sauce'),
(11, 'This actor/actress was born in Oxford, England'),
(11, 'This persons big break was a movie released in 2014 called "The Falling"'),
(11, 'This actor/actress was born on January 3rd, 1996'),
(12, 'This person was award the American medal of freedom by then President Barack Obama'),
(12, 'Robert De Niro has called this person "His favorite actress to work with"'),
(12, 'This person has a Sesame Street character named in their honour'),
(12, 'This person went to school with Sigourney Weaver'),
(12, 'This persons fans call themselves "Streepers"'),
(13, 'This person starred in what is highly regarded as the best film of all time, released in 1972'),
(13, 'This person is known for working with director Francis Ford Coppola'),
(13, 'In this persons final years, they were known to go into chatrooms to start arguements'),
(13, 'This person passed away in 2004'),
(13, 'This person received top billing in nearly every film they appeared in, even if not cast in the lead role.'),
(14, 'The day this person died, there was a tornado in Kansas'),
(14, 'This person won 5 Grammys over their career'),
(14, 'This person\'s most iconic role is also infamous for how horrible she was treated on set'),
(14, 'This person played a character named "Dorothy"'),
(14, 'This actor/actress inspired a character on "Gilligans Island"'),
(15, 'This person refuses to allow his likeness in video games or action figures'),
(15, 'This person has had many controversies over his long career'),
(15, 'This person is widely regarded as "The last true movie star"'),
(15, 'This person is well known for performing all of his dangerous stunts'),
(15, 'This person used to be married to Nicole Kidman'),
(16, 'This person has a sister named Dakota, who is also an actor'),
(16, 'She and her sister have a fear of thunderstorms and lightning.'),
(16, 'She is the only actress to play a leading role in films by Francis Ford Coppola and his daughter Sofia Coppola.'),
(16, 'This person most recently starred in a movie called "Sentimental Value"'),
(16, 'She refers to herself as a "Nepo-Sister" due to following in her sisters footsteps as an actor');


INSERT INTO ActorMovies(actor_id, movie_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(2, 6),
(2, 7),
(2, 8),
(2, 9),
(3, 10),
(3, 11),
(3, 12),
(3, 13),
(3, 14),
(3, 49),
(4, 15),
(4, 16),
(4, 17),
(4, 18),
(4, 19),
(5, 20),
(5, 21),
(5, 22),
(5, 23),
(5, 24),
(6, 25),
(6, 26),
(6, 27),
(7, 28),
(7, 29),
(7, 30),
(7, 31),
(7, 32),
(8, 33),
(8, 34),
(8, 35),
(8, 36),
(9, 37),
(9, 38),
(9, 39),
(10, 40),
(10, 41),
(10, 42),
(10, 43),
(10, 44),
(11, 33),
(11, 45),
(11, 46),
(11, 47),
(11, 48),
(11, 49),
(12, 50),
(12, 51),
(12, 52),
(12, 53),
(13, 54),
(13, 55),
(13, 56),
(13, 57),
(13, 58),
(13, 59),
(14, 60),
(14, 61),
(14, 62),
(14, 63),
(14, 64),
(15, 65),
(15, 66),
(15, 67),
(15, 68),
(15, 69),
(16, 70),
(16, 71),
(16, 72),
(16, 73);

SELECT a.actor_id, a.actor_name, m.movie_name, m.movie_id
FROM Actors a 
JOIN ActorMovies am ON am.actor_id = a.actor_id
JOIN Movies m ON m.movie_id = am.movie_id;